<template>
    <Head title="System Reports" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex justify-between items-center">
                <span>Reports & Analytics</span>
                <button class="bg-[#f5c242] text-[#0a1f44] hover:bg-yellow-500 px-4 py-2 rounded-lg font-semibold text-sm transition-colors shadow-sm">
                    + Generate Report
                </button>
            </div>
        </template>

        <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
            <div class="overflow-x-auto">
                <table class="w-full text-left border-collapse">
                    <thead>
                        <tr class="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
                            <th class="px-6 py-4 font-semibold">Report Title</th>
                            <th class="px-6 py-4 font-semibold">Type</th>
                            <th class="px-6 py-4 font-semibold">Generated By</th>
                            <th class="px-6 py-4 font-semibold">Date</th>
                            <th class="px-6 py-4 font-semibold text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100 text-sm">
                        <tr v-if="!reports || reports.data.length === 0">
                            <td colspan="5" class="px-6 py-8 text-center text-gray-500">No reports generated yet.</td>
                        </tr>
                        <tr v-for="report in (reports?.data || [])" :key="report.id" class="hover:bg-gray-50 transition-colors">
                            <td class="px-6 py-4 font-medium text-gray-900">{{ report.title }}</td>
                            <td class="px-6 py-4 text-gray-600 capitalize">{{ report.report_type.replace('_', ' ') }}</td>
                            <td class="px-6 py-4 text-gray-600">{{ report.generated_by_user?.name }}</td>
                            <td class="px-6 py-4 text-gray-500">{{ new Date(report.created_at).toLocaleDateString() }}</td>
                            <td class="px-6 py-4 text-right">
                                <a :href="report.file_path" target="_blank" class="text-blue-600 hover:text-blue-900 font-medium text-sm">Download</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </AuthenticatedLayout>
</template>

<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/inertia-vue3';

defineProps({
    reports: Object
});
</script>
