<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #1a202c;
            background-color: #ffffff;
            margin: 0;
            padding: 0;
            font-size: 8.5pt;
            line-height: 1.4;
        }
        .report-header {
            width: 100%;
            border-bottom: 3px solid #0a1f44;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }
        .logo-cell {
            width: 50px;
            vertical-align: middle;
        }
        .logo-cell img {
            width: 45px;
            height: 45px;
            display: block;
        }
        .title-cell {
            vertical-align: middle;
            padding-left: 10px;
        }
        .title-cell h1 {
            font-size: 20pt;
            font-weight: 800;
            color: #0a1f44;
            margin: 0;
            line-height: 1.1;
        }
        .title-cell p {
            font-size: 8.5pt;
            color: #4a5568;
            margin: 2px 0 0 0;
            text-transform: uppercase;
            font-weight: 600;
        }
        .metadata-cell {
            width: 35%;
            text-align: right;
            vertical-align: middle;
            font-size: 8.5pt;
            color: #718096;
            line-height: 1.5;
        }
        .report-title-bar {
            margin-top: 10px;
            margin-bottom: 20px;
            border-left: 4px solid #f5c242;
            padding-left: 12px;
        }
        .report-title {
            font-size: 14pt;
            font-weight: 800;
            color: #0a1f44;
            text-transform: uppercase;
            margin: 0;
        }
        .report-desc {
            font-size: 8.5pt;
            color: #718096;
            margin: 2px 0 0 0;
            font-weight: 500;
        }
        table.users-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 8pt;
        }
        th {
            background-color: #0a1f44;
            color: white;
            font-weight: bold;
            text-align: left;
            padding: 7px 9px;
            border: 1px solid #0a1f44;
            text-transform: uppercase;
            font-size: 7.5pt;
        }
        td {
            padding: 7px 9px;
            border: 1px solid #e2e8f0;
            color: #2d3748;
            vertical-align: middle;
        }
        tr:nth-child(even) td {
            background-color: #f8fafc;
        }
        .badge {
            display: inline-block;
            padding: 1px 5px;
            font-size: 7.5pt;
            font-weight: bold;
            border-radius: 3px;
            text-transform: uppercase;
        }
        .badge-active {
            background-color: #e6fffa;
            color: #319795;
            border: 1px solid #b2f5ea;
        }
        .badge-inactive {
            background-color: #fff5f5;
            color: #e53e3e;
            border: 1px solid #fed7d7;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 7.5pt;
            color: #a0aec0;
            border-top: 1px solid #e2e8f0;
            padding-top: 8px;
        }
    </style>
</head>
<body>
    <table class="report-header" style="width: 100%; border: none; background: transparent;">
        <tr style="border: none; background: transparent;">
            <td class="logo-cell" style="border: none; background: transparent;">
                <img src="{{ public_path('msu-logo-2.png') }}" />
            </td>
            <td class="title-cell" style="border: none; background: transparent;">
                <h1>MSUNLI</h1>
                <p>Midlands State University National Language Institute</p>
            </td>
            <td class="metadata-cell" style="border: none; background: transparent;">
                <p style="margin: 2px 0;"><strong>Generated By:</strong> {{ $generated_by }}</p>
                <p style="margin: 2px 0;"><strong>Date Compiled:</strong> {{ $generated_date }}</p>
                <p style="margin: 2px 0;"><strong>Format:</strong> PDF Report</p>
            </td>
        </tr>
    </table>

    <div class="report-title-bar">
        <h2 class="report-title">{{ $title }}</h2>
        <p class="report-desc">Scope: NLI Users Registry Export (Filtered)</p>
    </div>

    <table class="users-table">
        <thead>
            <tr>
                <th>User Name</th>
                <th>Email Address</th>
                <th>Phone</th>
                <th>Primary Role</th>
                <th>Unit / Department</th>
                <th>Institutional Section</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($users as $user)
                <tr>
                    <td style="font-weight: bold;">{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->phone ?? 'N/A' }}</td>
                    <td>{{ $user->msunliRole ? $user->msunliRole->name : ($user->roles->first() ? ucwords(str_replace('_', ' ', $user->roles->first()->name)) : 'Staff') }}</td>
                    <td>{{ $user->department ? $user->department->name : 'N/A' }}</td>
                    <td>{{ $user->section ? $user->section->name : 'N/A' }}</td>
                    <td>
                        <span class="badge badge-{{ $user->is_active ? 'active' : 'inactive' }}">
                            {{ $user->is_active ? 'Active' : 'Inactive' }}
                        </span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center; padding: 20px; color: #a0aec0;">No users matched the current filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        MSUNLI Management & Reporting Audit System &bull; Midlands State University &bull; Confidential
    </div>
</body>
</html>
